
CREATE TABLE users (
     id INT NOT NULL  AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    email VARCHAR (255) NOT NULL UNIQUE,
    password_hash VARCHAR (255) NOT NULL,
    user_status INT NOT NULL,
    user_role VARCHAR (25) NOT NULL
);


CREATE TABLE books (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    user_id INT NOT NULL,
    title VARCHAR (255) NOT NULL,
    author VARCHAR (255) NOT NULL,
    book_status INT NOT NULL,
    book_attrs JSON NOT NULL
);

CREATE TABLE carts (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    product_id INT NOT NULL ,
    user_id INT NOT NULL,
    cart_status INT NOT NULL,
    quantity INT NOT NULL
);


CREATE TABLE invoices (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    user_id INT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    invoice_status INT NOT NULL,
    invoice_attrs JSON NOT NULL
);

CREATE TABLE invoice_items (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    invoice_id INT NOT NULL REFERENCES invoices (id) ON DELETE CASCADE,
    produk_id INT NOT NULL,
    price INT NOT NULL,
    qty INT NOT NULL,
    item_status INT NOT NULL,
    item_attrs JSON NOT NULL
);

CREATE TABLE products (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    title VARCHAR (255) NOT NULL,
    quantity INT NOT NULL,
    price INT NOT NULL,
    product_status INT NOT NULL,
    product_attrs JSON NOT NULL
);

-- Add indexes
CREATE INDEX active_users ON users (id) ;
CREATE INDEX active_books ON books (title) ;
CREATE INDEX invoice ON invoices (id) ;
CREATE INDEX invoice_item ON invoice_items (id) ;
CREATE INDEX invoice_id ON invoice_items (invoice_id) ;
CREATE INDEX active_products ON products (id) ;
CREATE INDEX cart ON carts (id) ;